### ISSUE TITLE
Usprawnienia w kodzie

### ISSUE THREAD

**Issue by Mati365** [tomasz-paterka/salary_calculator#2]
- Brakuje jsdoc z typami argumentów w różnych metodach
- W takich przypadkach zamiast ternary operator używać zwykłych ifów, czytelniejsze są
https://github.com/tomasz-paterka/salary_calculator/blob/master/src/js/model/EmploymentContract.js#L9
- Możesz zrobić const {payment} = this; przed wszystkimi wywołaniami i nie odwoływać się do this.payment itp
https://github.com/tomasz-paterka/salary_calculator/blob/master/src/js/model/EmploymentContract.js#L12
- Brak nazewnictwa stałych np. 9.76, 6.50. Nie wiadomo za co odpowiadają
https://github.com/tomasz-paterka/salary_calculator/blob/master/src/js/model/EmploymentContract.js#L12
- Redundancja niektórych fragmentów kodu (powinno się je wyseparować do określonych współdzielonych helperów, o ile sie da)
https://github.com/tomasz-paterka/salary_calculator/blob/master/src/js/model/MandateContract.js
- Przeglądarki wspierają $ natywne, nie trzeba wywolywac metod document.*, 
https://github.com/tomasz-paterka/salary_calculator/blob/master/src/js/view/baseView.js#L3
poza tym nie trzymałbym tego w takim obiekcie, raczej lepiej jest zrobić mały wrapper na vanilla dom, który sam dodawałby sobie trochę "reaktywności". Widziałem takie na internecie. Chodzi mi o coś pokroju
```html
<div app:if={2 + 2 > 1}>
   <div app:click={() => this.abc();} />
</div>
```
to się da małym kosztem zrobić, kod fajniej wygląda i łatwiej się wspiera
- Lepiej używać metodyki BEM/BEMIT, rozbijać pliki na kilka mniejszych
https://github.com/tomasz-paterka/salary_calculator/blob/master/src/scss/style.scss 
rozmiar czcionki też lepiej robić na (r)em'ach
- Brakuje lintera
https://github.com/tomasz-paterka/salary_calculator

**Comment by tomasz-paterka** [comment]
Done :)
